### ISSUE TITLE
Inference/Prediction module

### ISSUE THREAD

**Issue by Arjunsankarlal** [Microsoft/SDNet#10]
Is there a way to test the trained model with our own data? Like passing passage and questions as input and getting answer span and score for it respectively.

**Comment by zcgzcgzcg1** [comment]
The best way is to organize your data in a json in the the same format as validation data in CoQA. Then, after executing Utils/CoQAPreprocess.py, you can train and evaluate SDNet model on your data.

**Comment by Arjunsankarlal** [comment]
You are correct @zcgzcgzcg1, But I have already trained the model with the CoQA data with the steps mentioned. And now I wanted to test that model with the set of document and questions I have, to see how the model extracts the answer from a document for a query based on it.

In that case I can't annotate the answer for the question from the corresponding paragraph. Is there an option currently available in your source code? If not kindly direct me on which part does the changes has to be made.
As far as I examined, the `predict` function in `SDNetTrainer.py`,

> 
    def predict(self, batch):
        self.network.eval()
        self.network.drop_emb = False

        # Run forward
        x, x_mask, x_char, x_char_mask, x_features, x_pos, x_ent, x_bert, x_bert_mask, x_bert_offsets, query, query_mask, \
        query_char, query_char_mask, query_bert, query_bert_mask, query_bert_offsets, ground_truth, context_str, context_words, \
        context_word_offsets, answers, context_id, turn_ids = batch

It needs all the params related to the document, question and the answers. I am looking to extract a paragraph from the document as the answer, based on the query.

**Comment by zcgzcgzcg1** [comment]
You can put a dummy answer in the corresponding part in the json. The code itself does not need to be changed if the format is the same as coqa dev json. 

For your trained model, add 'RESUME' in your configuration file and set 'MODEL_PATH' to your model path. Then the code will read your trained model and do evaluation first. You can hijack the prediction from variable "predictions" from line 102 in SDNetTrainer.py.
