### ISSUE TITLE
train with bert model

### ISSUE THREAD

**Issue by berton820** [Microsoft/SDNet#11]
the Requirement is PyTorch 0.4.0
but the line No.518 of Models/Bert/modeling.py is：
`module._load_from_state_dict(state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)`
the code is for Pytorch 0.4.1 ( https://github.com/huggingface/pytorch-pretrained-BERT/issues/122)
When i removed "local_metadata", it shows the ERROR as follows. could anyone can help?

Loading train json...
Loading dev json...
Epoch 0
Using BERT Large model
Loading tokenizer from test_coqa/bert-large-uncased/bert-large-uncased-vocab.txt
04/18/2019 11:27:58 - INFO - Models.Bert.tokenization -   loading vocabulary file test_coqa/bert-large-uncased/bert-large-uncased-vocab.txt
*****************
prev_ques   : 2
prev_ans    : 2
ques_max_len: 140
*****************
Using BERT Large model
Loading tokenizer from test_coqa/bert-large-uncased/bert-large-uncased-vocab.txt
04/18/2019 11:27:58 - INFO - Models.Bert.tokenization -   loading vocabulary file test_coqa/bert-large-uncased/bert-large-uncased-vocab.txt
*****************
prev_ques   : 2
prev_ans    : 2
ques_max_len: 140
*****************
/da1/home/berton/project/SDNet/Models/SDNet.py:286: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha_softmax = F.softmax(alpha)
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model.train()
  File "/da1/home/berton/project/SDNet/Models/SDNetTrainer.py", line 126, in train
    self.update(batch)
  File "/da1/home/berton/project/SDNet/Models/SDNetTrainer.py", line 165, in update
    query, query_mask, query_char, query_char_mask, query_bert, query_bert_mask, query_bert_offsets, len(context_words))
  File "/home/berton/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/da1/home/berton/project/SDNet/Models/SDNet.py", line 192, in forward
    x_cemb_mid = self.linear_sum(x_bert_output, self.alphaBERT, self.gammaBERT)
  File "/da1/home/berton/project/SDNet/Models/SDNet.py", line 292, in linear_sum
    res += t
RuntimeError: The expanded size of the tensor (1024) must match the existing size (388) at non-singleton dimension 2

**Comment by zcgzcgzcg1** [comment]
You're right. The requirement should be PyTorch 0.4.1. I just modified the description in readme. Thanks for reporting this.
