### ISSUE TITLE
train error with BERT model in pytorch 0.4.0 or 0.4.1

### ISSUE THREAD

**Issue by berton820** [Microsoft/SDNet#12]
**IN pytorch ==0.4.1** 
when i training model with Bert_large_model, it shows ERROR in NO.288 of  Models/SDNet.py as follows:
`
            t = output[i] * alpha_softmax[i] * gamma
`

/da1/home/berton/project/SDNet/Models/SDNet.py:286: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha_softmax = F.softmax(alpha)
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model.train()
  File "/da1/home/berton/project/SDNet/Models/SDNetTrainer.py", line 126, in train
    self.update(batch)
  File "/da1/home/berton/project/SDNet/Models/SDNetTrainer.py", line 165, in update
    query, query_mask, query_char, query_char_mask, query_bert, query_bert_mask, query_bert_offsets, len(context_words))
  File "/home/berton/py35/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/da1/home/berton/project/SDNet/Models/SDNet.py", line 192, in forward
    x_cemb_mid = self.linear_sum(x_bert_output, self.alphaBERT, self.gammaBERT)
  File "/da1/home/berton/project/SDNet/Models/SDNet.py", line 288, in linear_sum
    t = output[i] * alpha_softmax[i] * gamma
RuntimeError: sizes must be non-negative

**However,** I guess it's due to version issues(https://github.com/pytorch/pytorch/issues/11478) ，and change to Pytorch ==0.4.0 again, it shows another ERROR shows : 

/da1/home/berton/project/SDNet/Models/SDNet.py:286: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alpha_softmax = F.softmax(alpha)
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    model.train()
  File "/da1/home/berton/project/SDNet/Models/SDNetTrainer.py", line 126, in train
    self.update(batch)
  File "/da1/home/berton/project/SDNet/Models/SDNetTrainer.py", line 165, in update
    query, query_mask, query_char, query_char_mask, query_bert, query_bert_mask, query_bert_offsets, len(context_words))
  File "/home/berton/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/da1/home/berton/project/SDNet/Models/SDNet.py", line 192, in forward
    x_cemb_mid = self.linear_sum(x_bert_output, self.alphaBERT, self.gammaBERT)
  File "/da1/home/berton/project/SDNet/Models/SDNet.py", line 292, in linear_sum
    res += t
RuntimeError: The expanded size of the tensor (1024) must match the existing size (388) at non-singleton dimension 2

**Comment by ady-yu** [comment]
> **IN pytorch ==0.4.1**
> when i training model with Bert_large_model, it shows ERROR in NO.288 of Models/SDNet.py as follows:
> `t = output[i] * alpha_softmax[i] * gamma`
> 
> /da1/home/berton/project/SDNet/Models/SDNet.py:286: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
> alpha_softmax = F.softmax(alpha)
> Traceback (most recent call last):
> File "main.py", line 35, in
> model.train()
> File "/da1/home/berton/project/SDNet/Models/SDNetTrainer.py", line 126, in train
> self.update(batch)
> File "/da1/home/berton/project/SDNet/Models/SDNetTrainer.py", line 165, in update
> query, query_mask, query_char, query_char_mask, query_bert, query_bert_mask, query_bert_offsets, len(context_words))
> File "/home/berton/py35/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/da1/home/berton/project/SDNet/Models/SDNet.py", line 192, in forward
> x_cemb_mid = self.linear_sum(x_bert_output, self.alphaBERT, self.gammaBERT)
> File "/da1/home/berton/project/SDNet/Models/SDNet.py", line 288, in linear_sum
> t = output[i] * alpha_softmax[i] * gamma
> RuntimeError: sizes must be non-negative
> 
> **However,** I guess it's due to version issues([pytorch/pytorch#11478](https://github.com/pytorch/pytorch/issues/11478)) ，and change to Pytorch ==0.4.0 again, it shows another ERROR shows :
> 
> /da1/home/berton/project/SDNet/Models/SDNet.py:286: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
> alpha_softmax = F.softmax(alpha)
> Traceback (most recent call last):
> File "main.py", line 35, in
> model.train()
> File "/da1/home/berton/project/SDNet/Models/SDNetTrainer.py", line 126, in train
> self.update(batch)
> File "/da1/home/berton/project/SDNet/Models/SDNetTrainer.py", line 165, in update
> query, query_mask, query_char, query_char_mask, query_bert, query_bert_mask, query_bert_offsets, len(context_words))
> File "/home/berton/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in **call**
> result = self.forward(*input, **kwargs)
> File "/da1/home/berton/project/SDNet/Models/SDNet.py", line 192, in forward
> x_cemb_mid = self.linear_sum(x_bert_output, self.alphaBERT, self.gammaBERT)
> File "/da1/home/berton/project/SDNet/Models/SDNet.py", line 292, in linear_sum
> res += t
> RuntimeError: The expanded size of the tensor (1024) must match the existing size (388) at non-singleton dimension 2

how do you solve this prolem
