### ISSUE TITLE
Please add support for pytorch 1.0.0 and msgpack-numpy 0.4.4.1

### ISSUE THREAD

**Issue by ineWsTut** [Microsoft/SDNet#3]
I used msgpack-numpy==0.4.4.1, but the code goes wrong when store and load preprocessed file. 

I used pytorch==1.0.0, but it goes wrong when starting training.

So I have to downgrade to msgpack-numpy==0.4.3.2 and pytorch==0.4.1, and they worked!

I would be very grateful if you could add support for the higher version, thanks~

**Comment by zcgzcgzcg1** [comment]
Good suggestion. We will possibly do that in the future.

**Comment by DbrRoxane** [comment]
OMG @ssdf93 , thanks for this issue, it solved all my problems. @zcgzcgzcg1 , you really should specify the exact packages to use on the README or (and it would be the best solution) write a requirement.txt.
