### ISSUE TITLE
tf version

### ISSUE THREAD

**Issue by Decalogue** [Microsoft/SDNet#4]
Hi!
I use tf 1.10.0 to transfer bert ckpt into pytorch_model.bin. Could you tell me the tf version?
When I run the source code, this error occurred:
TypeError: _load_from_state_dict() takes 7 positional arguments but 8 were given

Thank you!

**Comment by zcgzcgzcg1** [comment]
Hope this can help: https://github.com/huggingface/pytorch-pretrained-BERT/issues/122

**Comment by Decalogue** [comment]
Thank you so much!
