### ISSUE TITLE
When context is larger than BERT_MAX_LEN

### ISSUE THREAD

**Issue by BiuBiuBiLL** [Microsoft/SDNet#5]
In the forward function here: (https://github.com/Microsoft/SDNet/blob/master/Models/Bert/Bert.py#L57)

You divide the tokens to deal with the context window larger than BERT_MAX_LEN. However, if you do this, then in the subsequent loops, the truncated BERT tokens are no longer valid "bertify" tokens, since it does not contain `<CLS>` as the beginning of the input sentence, will it cause a problem to get correct BERT representations ?

**Comment by zcgzcgzcg1** [comment]
You're right that the second windows does not contain <CLS>. You can try adding <CLS> and see whether it can improve performance.
