### ISSUE TITLE
Mapping Bert model contents

### ISSUE THREAD

**Issue by Arjunsankarlal** [Microsoft/SDNet#6]
I have followed all the steps as mentioned in the readme. In the file structure given, inside the bert-large-uncased folder, it is mentioned as 

bert-large-uncased-vocab.txt
bert_config.json
pytorch_model.bin

but in the actual models downloaded from the bert repo will have the following,
vocab.txt --> bert-large-uncased-vocab.txt
bert_config.json  --> bert_config.json
bert_model.ckpt.index
bert_model.ckpt.meta
bert_model.ckpt.data-00000-of-00001

among the other three I tried replacing each one of them as pytorch_model.bin but each one of them is giving a pickling error, only the key value displayed for error changes.

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    model.train()
  File "/home/crm-di/SDNet/Models/SDNetTrainer.py", line 66, in train
    self.setup_model(vocab_embedding)
  File "/home/crm-di/SDNet/Models/SDNetTrainer.py", line 137, in setup_model
    self.network = SDNet(self.opt, vocab_embedding)
  File "/home/crm-di/SDNet/Models/SDNet.py", line 63, in __init__
    self.Bert = Bert(self.opt)
  File "/home/crm-di/SDNet/Models/Bert/Bert.py", line 24, in __init__
    self.bert_model = BertModel.from_pretrained(model_file)
  File "/home/crm-di/SDNet/Models/Bert/modeling.py", line 505, in from_pretrained
    state_dict = torch.load(weights_path)
  File "/home/crm-di/SDNet/env/lib/python3.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/crm-di/SDNet/env/lib/python3.7/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '\x0a'.

Can more details about the bert models could be added?

**Comment by zcgzcgzcg1** [comment]
The ckpt is from Tensorflow. Please follow Huggingface's tutorial to convert it into .bin file: https://github.com/huggingface/pytorch-pretrained-BERT#command-line-interface

Or, more easily, directly download from the following links provided by Huggingface:
{
    'bert-base-uncased': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz",
    'bert-large-uncased': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased.tar.gz",
    'bert-base-cased': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased.tar.gz",
    'bert-base-multilingual': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual.tar.gz",
    'bert-base-chinese': "https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese.tar.gz",
}

**Comment by Arjunsankarlal** [comment]
Thanks, it worked and got the vocab files from your repo :)
