### ISSUE TITLE
Train loss NaN when previous QA is set to 0

### ISSUE THREAD

**Issue by Ajanulk** [Microsoft/SDNet#8]
When I set previous QA to 0 in conf, the train loss met nan. How can I solve it?

**Comment by zcgzcgzcg1** [comment]
It may happen that certain weights get very large. Try using smaller gradient clipping (like 1, 0.1).

**Comment by Ajanulk** [comment]
> 
> 
> It may happen that certain weights get very large. Try using smaller gradient clipping (like 1, 0.1).

@zcgzcgzcg1 Thanks for your reply. But it doesnt work according to your suggestion (gradient clipping 1, 0.1).
